  name: Commit and Push Changes
  run: |
    git config --global user.email "action@github.com"
    git config --global user.name "GitHub Action"
    git commit -am "ğŸ” Update tracker timestamp: $ts" || echo "No changes"
    git push
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
